/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// 0: Include standard integer types header for fixed-width integer types
#include <stdint.h>
#include "gpio.h"
#include "stm32f1xx.h"
#include "SysTick.h"
#include "uart.h"
// 1: GPIO_TypeDef structure definition
/*typedef struct {
  volatile uint32_t CRL;    // 0x00 Config Register Low (CRL) pin 0 - 7
  volatile uint32_t CRH;    // 0x04 Config Register High (CRH) pin 8 - 15
  volatile uint32_t IDR;    // 0x08 Input Data Register (IDR)
  volatile uint32_t ODR;    // 0x0C Output Data Register (ODR)
  volatile uint32_t BSRR;   // 0x10 Bit Set/Reset Register (BSRR)
  volatile uint32_t BRR;    // 0x14
  volatile uint32_t LCKR;   // 0x18
} GPIO_TypeDef;

// 2: RCC_TypeDef structure definition
typedef struct {
  volatile uint32_t CR;        // 0x00
  volatile uint32_t CFGR;      // 0x04
  volatile uint32_t CIR;       // 0x08
  volatile uint32_t APB2RSTR;  // 0x0C
  volatile uint32_t APB1RSTR;  // 0x10
  volatile uint32_t AHBENR;    // 0x14
  volatile uint32_t APB2ENR;   // 0x18
  volatile uint32_t APB1ENR;   // 0x1C
  volatile uint32_t BDCR;      // 0x20
  volatile uint32_t CSR;       // 0x24
} RCC_TypeDef;


// 3: Base address definitions
#define RCC_BASE   0x40021000
//GPIO from A to E address bases definitions
#define GPIOA_BASE 0x40010800
#define GPIOB_BASE 0x40010C00
#define GPIOC_BASE 0x40011000
#define GPIOD_BASE 0x40011400
#define GPIOE_BASE 0x40011800

// 4: Peripheral pointer definitions
#define RCC		    ((RCC_TypeDef*) RCC_BASE)
#define GPIOA		((GPIO_TypeDef*)GPIOA_BASE)
#define GPIOB 		((GPIO_TypeDef*)GPIOB_BASE)
#define GPIOC 		((GPIO_TypeDef*)GPIOC_BASE)
#define GPIOD 		((GPIO_TypeDef*)GPIOD_BASE)
#define GPIOE 		((GPIO_TypeDef*)GPIOE_BASE)
*/


// System Tick define
#define CTRL_ENABLE (1U << 0)
#define CTRL_CLOCKSRC (1U << 2)
#define CTRL_COUNTFLAG (1U << 16)






#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	//led_init();
	uart_init();

	while(1)
{

    //led_on();
	//systick_delay(500);

	//led_off();
    //systick_delay(500);

	//systick_delay(1000);
	//led_toggle();
		uart_print("testing...\r\n");

		char c = uart_receive();
		uart_transmit(c);
		for (volatile int i = 0; i < 1000000; i++);
}
}
